---
name: "Check version bump"

on:
  pull_request:
    branches: [master]

jobs:
  check_version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: $(( ${{ github.event.pull_request.commits || 0 }} + 1 ))

      - name: Git log
        run: git log -n20 --color --oneline --decorate

      - name: Check version bump
        run: .github/scripts/check_version_bump.sh
        env:
          BASE_REF: ${{ github.event.pull_request.base.sha }}
          HEAD_REF: ${{ github.event.pull_request.head.sha }}
